version: '3.8'

services:

  backend:
    build: .
    ports:
      - "9090:9090"
    env_file:
      - .env
    environment:
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - spring-mysql-net

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-mysql-net

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:

networks:
  spring-mysql-net:
