# ===================================================================
# EMAIL (Gmail) Configuration
# Use environment variables to set these values in production.
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===================================================================
# TWILIO Configuration
# Use environment variables to set these values in production.
# ===================================================================
app.twilio.account-sid=${TWILIO_ACCOUNT_SID}
app.twilio.auth-token=${TWILIO_AUTH_TOKEN}
app.twilio.phone-number=${TWILIO_PHONE_NUMBER}